// Code generated by cuelang.org/go/pkg/gen. DO NOT EDIT.
package sha512

Size:      64
Size224:   28
Size256:   32
Size384:   48
BlockSize: 128
funcs: Sum512: {
	in: #A0: bytes | string
	out: bytes | string
}
funcs: Sum384: {
	in: #A0: bytes | string
	out: bytes | string
}
funcs: Sum512_224: {
	in: #A0: bytes | string
	out: bytes | string
}
funcs: Sum512_256: {
	in: #A0: bytes | string
	out: bytes | string
}
