// Code generated by cuelang.org/go/pkg/gen. DO NOT EDIT.

package hmac

import (
	"cuelang.org/go/internal/core/adt"
	"cuelang.org/go/pkg/internal"

	_ "embed"
)

func init() {
	internal.Register("crypto/hmac", pkg)
}

//go:embed pkg.cue
var cueDecls string

var _ = adt.TopKind // in case the adt package isn't used

var pkg = &internal.Package{
	Funcs: map[string]func(c *internal.CallCtxt){
		"Sign": func(c *internal.CallCtxt) {
			hashName, key, data := c.String(0), c.Bytes(1), c.Bytes(2)
			if c.Do() {
				c.Ret, c.Err = Sign(hashName, key, data)
			}
		},
	},
	CUE: cueDecls,
}
