// Code generated by cuelang.org/go/pkg/gen. DO NOT EDIT.
package hex

funcs: EncodedLen: {
	in: [{
		name: "n"
		type: int64
	}]
	out: int64
}
funcs: DecodedLen: {
	in: [{
		name: "x"
		type: int64
	}]
	out: int64
}
funcs: Decode: {
	in: [{
		name: "s"
		type: string
	}]
	out: bytes | string
}
funcs: Dump: {
	in: [{
		name: "data"
		type: bytes | string
	}]
	out: string
}
funcs: Encode: {
	in: [{
		name: "src"
		type: bytes | string
	}]
	out: string
}
