// Code generated by cuelang.org/go/pkg/gen. DO NOT EDIT.
package html

funcs: Escape: {
	in: [{
		name: "s"
		type: string
	}]
	out: string
}
funcs: Unescape: {
	in: [{
		name: "s"
		type: string
	}]
	out: string
}
