// Code generated by cuelang.org/go/pkg/gen. DO NOT EDIT.
package struct

funcs: MinFields: {
	in: [{
		name: "object"
		type: {...}
	}, {
		name: "n"
		type: int64
	}]
	out: _
}
funcs: MaxFields: {
	in: [{
		name: "object"
		type: {...}
	}, {
		name: "n"
		type: int64
	}]
	out: bool
}
