// Code generated by cuelang.org/go/pkg/gen. DO NOT EDIT.
package struct

funcs: MinFields: {
	in: {
		#A0: {...}
		#A1: int64
	}
	out: _
}
funcs: MaxFields: {
	in: {
		#A0: {...}
		#A1: int64
	}
	out: bool
}
