// Code generated by cuelang.org/go/pkg/gen. DO NOT EDIT.
package base64

funcs: EncodedLen: {
	in: {
		#A0: _
		#A1: int64
	}
	out: int64
}
funcs: DecodedLen: {
	in: {
		#A0: _
		#A1: int64
	}
	out: int64
}
funcs: Encode: {
	in: {
		#A0: _
		#A1: bytes | string
	}
	out: string
}
funcs: Decode: {
	in: {
		#A0: _
		#A1: string
	}
	out: bytes | string
}
