// Code generated by cuelang.org/go/pkg/gen. DO NOT EDIT.
package sha256

Size:      32
Size224:   28
BlockSize: 64
funcs: Sum256: {
	in: [{
		name: "data"
		type: bytes | string
	}]
	out: bytes | string
}
funcs: Sum224: {
	in: [{
		name: "data"
		type: bytes | string
	}]
	out: bytes | string
}
