// Code generated by cuelang.org/go/pkg/gen. DO NOT EDIT.
package sha256

Size:      32
Size224:   28
BlockSize: 64
funcs: Sum256: {
	in: #A0: bytes | string
	out: bytes | string
}
funcs: Sum224: {
	in: #A0: bytes | string
	out: bytes | string
}
