// Code generated by cuelang.org/go/pkg/gen. DO NOT EDIT.

package sha256

import (
	"cuelang.org/go/internal/core/adt"
	"cuelang.org/go/pkg/internal"
)

func init() {
	internal.Register("crypto/sha256", pkg)
}

var _ = adt.TopKind // in case the adt package isn't used

var pkg = &internal.Package{
	Funcs: map[string]func(c *internal.CallCtxt){
		"Sum256": func(c *internal.CallCtxt) {

			data := c.Bytes(0)
			if c.Do() {
				c.Ret = Sum256(data)
			}
		},
		"Sum224": func(c *internal.CallCtxt) {

			data := c.Bytes(0)
			if c.Do() {
				c.Ret = Sum224(data)
			}
		},
	},
	CUE: `{
	_
	exports: {
		Sum256: {
			in: [...#Arg] & [{
				name: "data"
				type: bytes | string
			}]
			out: bytes | string
		}
		Sum224: {
			in: [...#Arg] & [{
				name: "data"
				type: bytes | string
			}]
			out: bytes | string
		}
		Size224?:   28
		Size?:      32
		BlockSize?: 64
	}
}`,
}
