// Code generated by cuelang.org/go/pkg/gen. DO NOT EDIT.

package tabwriter

import (
	"cuelang.org/go/internal/core/adt"
	"cuelang.org/go/pkg/internal"
)

func init() {
	internal.Register("text/tabwriter", pkg)
}

var _ = adt.TopKind // in case the adt package isn't used

var pkg = &internal.Package{
	Funcs: map[string]func(c *internal.CallCtxt){
		"Write": func(c *internal.CallCtxt) {

			data := c.Value(0)
			if c.Do() {
				c.Ret, c.Err = Write(data)
			}
		},
	},
	CUE: `{
	_
	exports: {
		Write: {
			in: [...#Arg] & [{
				name: "data"
				type: _
			}]
			out: string
		}
	}
}`,
}
