// Code generated by cuelang.org/go/pkg/gen. DO NOT EDIT.

package csv

import (
	"cuelang.org/go/internal/core/adt"
	"cuelang.org/go/pkg/internal"
)

func init() {
	internal.Register("encoding/csv", pkg)
}

var _ = adt.TopKind // in case the adt package isn't used

var pkg = &internal.Package{
	Funcs: map[string]func(c *internal.CallCtxt){
		"Encode": func(c *internal.CallCtxt) {

			x := c.Value(0)
			if c.Do() {
				c.Ret, c.Err = Encode(x)
			}
		},
		"Decode": func(c *internal.CallCtxt) {

			r := c.Reader(0)
			if c.Do() {
				c.Ret, c.Err = Decode(r)
			}
		},
	},
	CUE: `{
	_
	exports: {
		Encode: {
			in: [...#Arg] & [{
				name: "x"
				type: _
			}]
			out: string
		}
		Decode: {
			in: [...#Arg] & [{
				name: "r"
				type: bytes | string
			}]
			out: [...]
		}
	}
}`,
}
