// Code generated by cuelang.org/go/pkg/gen. DO NOT EDIT.
package template

funcs: Execute: {
	in: {
		#A0: string
		#A1: _
	}
	out: string
}
funcs: HTMLEscape: {
	in: #A0: string
	out: string
}
funcs: JSEscape: {
	in: #A0: string
	out: string
}
