// Code generated by cuelang.org/go/pkg/gen. DO NOT EDIT.
package template

funcs: Execute: {
	in: [{
		name: "templ"
		type: string
	}, {
		name: "data"
		type: _
	}]
	out: string
}
funcs: HTMLEscape: {
	in: [{
		name: "s"
		type: string
	}]
	out: string
}
funcs: JSEscape: {
	in: [{
		name: "s"
		type: string
	}]
	out: string
}
